services:
  traefik:
    image: traefik:3.2.0
    command:
      - "--api.dashboard=true"                      
      - "--entrypoints.http.address=:80"            
      - "--entrypoints.https.address=:443"          
      - "--providers.docker=true"                   
      - "--providers.docker.exposedbydefault=false" 
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"       
      - "443:443"     
      - "8080:8080"   
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/letsencrypt:/letsencrypt"              
    restart: unless-stopped

  django:
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    restart: unless-stopped
